// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

// Supabase configuration
const SUPABASE_URL = "https://qancoxgobmcxzerbsiqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhbmNveGdvYm1jeHplcmJzaXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTkwNjMsImV4cCI6MjA2MDA5NTA2M30._Uc9Uwoo1hqdlHvwa7rfvr2ENwlYKIb-eaFkasVDHRM";

if (!SUPABASE_URL) {
  throw new Error('Missing SUPABASE_URL');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing SUPABASE_PUBLISHABLE_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with types
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
    },
  }
);

// Export types for convenience
export type { Database };